### model
model_name_or_path: facebook/opt-1.3b

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: wikiqa
template: llama3
cutoff_len: 2048
max_samples: 100000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ./train_search
logging_steps: 8
save_steps: 100000000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 1.0e-7
num_train_epochs: 3.0
lr_scheduler_type: constant
warmup_ratio: 0.0
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 128
