WORK_DIR = "."
CONDA_ACTIVATE_ADDR = "."
CONDA_ENV_NAME = ""

MAX_PENDING_TIMES = 100
PENDING_RETRY_INTERVAL = 10
MATAIN_GRS_TARGET_INTERVAL = 10

MAX_GRAD_DIM = 5000000
BETA = 0.9
GRT_EMA = 0.7

GRS_ACC_TIMES = 5
GRS_MONITOR_INTERVAL = 200
GRS_CHUNKS = 500

PROFILE_WINDOW = 5

GRT_TARGET = 1.33
GRS_TARGET = 0
MAX_BS_RATIO = 16

GRS_ADJUST_DELTA = 0.1
GRS_LOWER_BOUND = -0.5
GRS_UPPER_BOUND = 0.5

RANDOM_SEED = 42